# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [4]:
import pandas as pd

url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [5]:
chipo = pd.read_csv(url , sep="\t")
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

### Step 4. How many products cost more than $10.00?

In [6]:
chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype(float)
chipo['product_price'] = chipo['item_price'] / chipo['quantity']
chipo

,order_id,quantity,item_name,choice_description,item_price,product_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75

### Step 5. What is the price of each item? 
###### print a data frame with only three columns item_name choice_description and product_price

In [7]:
chipo[['item_name', 'choice_description' , 'product_price']]

,item_name,choice_description,product_price
0,Chips and Fresh Tomato Salsa,NaN,2.39
1,Izze,[Clementine],3.39
2,Nantucket Nectar,[Apple],3.39
3,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",8.49
...,...,...,...
4617,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

### Step 6. Sort by the name of the item

In [8]:
chipo['item_name'].sort_values()

3389    6 Pack Soft Drink
341     6 Pack Soft Drink
1849    6 Pack Soft Drink
1860    6 Pack Soft Drink
2713    6 Pack Soft Drink
              ...
2384    Veggie Soft Tacos
781     Veggie Soft Tacos
2851    Veggie Soft Tacos
1699    Veggie Soft Tacos
1395    Veggie Soft Tacos
Name: item_name, Length: 4622, dtype: str

### Step 7. What was the quantity of the most expensive item ordered?

In [9]:
chipo.loc[chipo['item_price'].idxmax(), 'quantity']

np.int64(15)

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [10]:
chipo[chipo["item_name"] == 'Veggie Salad Bowl']['quantity'].sum()

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [15]:
chipo[(chipo['item_name'] == 'Canned Soda')& (chipo['quantity'] >1)]

,order_id,quantity,item_name,choice_description,item_price,product_price
18,9,2,Canned Soda,[Sprite],2.18,1.09
51,23,2,Canned Soda,[Mountain Dew],2.18,1.09
162,73,2,Canned Soda,[Diet Coke],2.18,1.09
171,76,2,Canned Soda,[Diet Dr. Pepper],2.18,1.09
350,150,2,Canned Soda,[Diet Coke],2.18,1.09
352,151,2,Canned Soda,[Coca Cola],2.18,1.09
698,287,2,Canned Soda,[Coca Cola],2.18,1.09
700,288,2,Canned Soda,[Coca Cola],2.18,1.09
909,376,2,Canned Soda,[Mountain Dew],2.18,1.09
1091,450,2,Canned Soda,[Dr. Pepper],2.18,1.09
1092,450,2,Canned Soda,[Coca Cola],2.18,1.09
1944,787,2,Canned Soda,[Dr. Pepper],2.18,1.09
2135,859,2,Canned Soda,[Diet Coke],2.18,1.09
2235,901,4,Canned Soda,[Sprite],4.36,1.09
2905,1156,2,Canned Soda,[Coca Cola],2.18,1.09
2906,1156,2,Canned Soda,[Sprite],2.18,1.09
3152,1258,2,Canned Soda,[Dr. Pepper],2.18,1.09
3364,1349,2,Canned Soda,[Coca Cola],2.18,1.09
3592,1440,2,Canned Soda,[Diet Coke],2.18,1.09
3866,1550,2,Canned Soda,[Mountain Dew],2.18,1.09