# M4.Ex1: Housing Prices Model (PyCaret)

- Run: [**Open In Colab**](https://colab.research.google.com/github/HassanAlgoz/B5/blob/main/content/W3/M6/exercises/ex1_pycaret_regression.ipynb)

## Exercise

Your task is to follow the steps outlined here, and apply them on the **California Housing Dataset** below:

- [**🚀 Regression**](https://pycaret.gitbook.io/docs/get-started/quickstart#regression)
    - Setup
    - Compare Models
    - Analyze Model
    - Predictions
    - Save the model

## California Housing Prices Dataset


Find and download the dataset from Kaggle at [California Housing Dataset](https://www.kaggle.com/datasets/dhirajnirne/california-housing-data).

According to [keras.io](https://keras.io/api/datasets/california_housing/):
 
> This dataset was obtained from the StatLib repository.
> 
> It's a continuous regression dataset with 20,640 samples with 8 features each.
> 
> The target variable is a scalar: the median house value for California districts, in dollars.
> 
> The 8 input features are the following:
> 
> - MedInc: median income in block group
> - HouseAge: median house age in block group
> - AveRooms: average number of rooms per household
> - AveBedrms: average number of bedrooms per household
> - Population: block group population
> - AveOccup: average number of household members
> - Latitude: block group latitude
> - Longitude: block group longitude
> 
> This dataset was derived from the 1990 U.S. census, using one row per census block group. A block group is the smallest geographical unit for which the U.S. Census Bureau publishes sample data (a block group typically has a population of 600 to 3,000 people).
> 
> A household is a group of people residing within a home. Since the average number of rooms and bedrooms in this dataset are provided per household, these columns may take surprisingly large values for block groups with few households and many empty houses, such as vacation resorts.

### Load the data

In [1]:
# pd.read_csv("../../../datasets/california_housing.csv").head()
import kagglehub

import pandas as pd
import os
os.environ["OMP_NUM_THREADS"] = "1"
# Download latest version
path = kagglehub.dataset_download("dhirajnirne/california-housing-data")

print("Path to dataset files:", path)


print(os.listdir(path))

file_path = path + "/housing.csv"   # adjust name if different
df = pd.read_csv(file_path)

Path to dataset files: /Users/woroodmup/.cache/kagglehub/datasets/dhirajnirne/california-housing-data/versions/1
['housing.csv']

In [2]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

**Task**: Your model should learn from this data and be able to predict the median housing price (`median_house_value`) in any district, given all the other metrics.

Please read the above dataset description to understand what the features mean.

In [3]:
print(df.columns.tolist())

['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value', 'ocean_proximity']

In [4]:
from pycaret.regression import RegressionExperiment
s = RegressionExperiment()
df_small = df.sample(3000, random_state=42)

s.setup(
    data=df_small,
    target='median_house_value',
    verbose=False,
    session_id=42,
    n_jobs=1
)

In [ ]:
best_model = s.compare_models()
print(best_model)

LGBMRegressor(n_jobs=1, random_state=42)

In [ ]:
predictions = s.predict_model(best_model)
predictions.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value,prediction_label
5182,-118.250000,33.939999,37.0,1002.0,270.0,1092.0,273.0,1.6333,<1H OCEAN,94500.0,96924.141495
6769,-118.150002,34.099998,52.0,4325.0,823.0,1927.0,795.0,3.9485,<1H OCEAN,419100.0,251999.709759
15066,-116.970001,32.790001,19.0,4108.0,1101.0,2971.0,1006.0,1.9893,<1H OCEAN,112500.0,119704.680715
19296,-122.820000,38.400002,40.0,2406.0,423.0,1054.0,426.0,3.8846,<1H OCEAN,215900.0,188073.119503
19246,-122.730003,38.459999,14.0,4042.0,1298.0,2323.0,1158.0,2.0651,<1H OCEAN,135400.0,175539.652789

In [ ]:
s.save_model(best_model, 'housing_price_model')
print("Model saved successfully!")

Transformation Pipeline and Model Successfully Saved
Model saved successfully!